In [23]:
import pandas as pd
import numpy as np
import pyproj
import folium


df = pd.read_csv('./hostipal.csv', encoding='cp949', usecols=['좌표정보(x)', '좌표정보(y)'])



df['좌표정보(x)'] = pd.to_numeric(df['좌표정보(x)'], errors='coerce')
df['좌표정보(y)'] = pd.to_numeric(df['좌표정보(y)'], errors='coerce')

df = df.dropna() #NaN값이 잇는 데이터 제거하기
df.index = range(len(df))
df

좌표정보(x)      좌표정보(y)
0     299970.3318  176114.7080
1     299722.4204  177131.7783
2     297272.3901  159579.1491
3     394946.0000  213423.0000
4     337000.3444  232019.5924
...           ...          ...
4373  330015.5640  410050.9824
4374  277834.5715  465448.8405
4375  287814.9568  426438.3922
4376  302989.2568  508172.7999
4377  231180.8067  316902.5708

[4378 rows x 2 columns]

In [25]:
def project_array(coord, p1_type, p2_type):
    """
    좌표계 변환 함수
    - coord: x, y 좌표 정보가 담긴 NumPy Array
    - p1_type: 입력 좌표계 정보 ex) epsg:5179
    - p2_type: 출력 좌표계 정보 ex) epsg:4326
    """
    p1 = pyproj.Proj(init=p1_type)
    p2 = pyproj.Proj(init=p2_type)
    fx, fy = pyproj.transform(p1, p2, coord[:, 0], coord[:, 1])
    return np.dstack([fx, fy])[0]

In [26]:
coord = np.array(df)

coord

array([[299970.3318, 176114.708 ],
       [299722.4204, 177131.7783],
       [297272.3901, 159579.1491],
       ...,
       [287814.9568, 426438.3922],
       [302989.2568, 508172.7999],
       [231180.8067, 316902.5708]])

In [27]:
p1_type = "epsg:2097"
p2_type = "epsg:4326"

result = project_array(coord, p1_type, p2_type)
result

C:\Users\by_wh\anaconda3\lib\site-packages\pyproj\crs\crs.py:130: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)
C:\Users\by_wh\anaconda3\lib\site-packages\pyproj\crs\crs.py:130: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)
C:\Users\by_wh\AppData\Local\Temp/ipykernel_17840/3581348372.py:10: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  fx, fy 

array([[128.0940537 ,  35.07912326],
       [128.09145814,  35.08831363],
       [128.06254526,  34.93036481],
       ...,
       [127.98880983,  37.33583272],
       [128.1715528 ,  38.07052359],
       [127.34528268,  36.35244731]])

In [32]:
df['경도'] = result[:, 0]
df['위도'] = result[:, 1]

df.tail()




좌표정보(x)      좌표정보(y)          경도         위도
4373  330015.5640  410050.9824  128.462026  37.183282
4374  277834.5715  465448.8405  127.880328  37.688163
4375  287814.9568  426438.3922  127.988810  37.335833
4376  302989.2568  508172.7999  128.171553  38.070524
4377  231180.8067  316902.5708  127.345283  36.352447

In [38]:
ndf = pd.read_csv('./pharmacy_d.csv', encoding='cp949', usecols=['사업장명', '좌표정보(x)', '좌표정보(y)'])

ndf['좌표정보(x)'] = pd.to_numeric(ndf['좌표정보(x)'], errors='coerce')
ndf['좌표정보(y)'] = pd.to_numeric(ndf['좌표정보(y)'], errors='coerce')

ndf = ndf.dropna()

ndf.columns = ['corp_name', 'longitude', 'latitude']
ndf = ndf.set_index('corp_name')

ndf

longitude     latitude
corp_name                          
란약국        193786.8302  185954.5194
메디팜건강약국    194075.2441  184984.4186
좋은약국       193146.4005  186088.1065
라포약국       194270.1072  184985.2783
뷰티온누리약국    190911.6877  187580.1799
...                ...          ...
산들약국       212334.9585  450346.7907
바라기한약국     204393.9045  446390.5678
딸기약국       207642.1445  458161.8328
새봄이온누리약국   171649.4169  459680.7989
햇살약국       167324.8246  460347.8841

[23675 rows x 2 columns]

In [39]:
coord_n = np.array(ndf)
coord_n

array([[193786.8302, 185954.5194],
       [194075.2441, 184984.4186],
       [193146.4005, 186088.1065],
       ...,
       [207642.1445, 458161.8328],
       [171649.4169, 459680.7989],
       [167324.8246, 460347.8841]])

In [40]:
p1_type = "epsg:2097"
p2_type = "epsg:4326"

result_n = project_array(coord_n, p1_type, p2_type)
result_n

C:\Users\by_wh\anaconda3\lib\site-packages\pyproj\crs\crs.py:130: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)
C:\Users\by_wh\anaconda3\lib\site-packages\pyproj\crs\crs.py:130: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)
C:\Users\by_wh\AppData\Local\Temp/ipykernel_17840/3581348372.py:10: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  fx, fy 

array([[126.92971436,  35.17274379],
       [126.93288742,  35.16400152],
       [126.92268301,  35.17394368],
       ...,
       [127.08446671,  37.62577367],
       [126.67668799,  37.63905122],
       [126.62766181,  37.64491751]])

In [41]:
ndf['longitude'] = result[:, 0]
ndf['latitude'] = result[:, 1]

ndf.to_excel('./Pharmacy_t.xlsx')

ValueError: Length of values (4378) does not match length of index (23675)

In [1]:
import pandas as pd
import numpy as np
import pyproj
import folium

In [2]:
df = pd.read_json('./Hospital_t .json')

df

corp_name   longitude   latitude
0     의료법인 행복한의료재단 사천중앙요양병원  128.094054  35.079123
1                    사천동희병원  128.091458  35.088314
2        의료법인 삼포의료재단 현대요양병원  128.062545  34.930365
3                      양산병원  129.143769  35.401293
4                   프라임요양병원  128.509310  35.578490
...                     ...         ...        ...
4373                 푸른사랑병원  128.462026  37.183282
4374          미성의료재단 아름다운병원  127.880328  37.688163
4375                   영광병원  127.988810  37.335833
4376                 인제고려병원  128.171553  38.070524
4377  의료법인 리노의료재단 유성웰니스재활병원  127.345283  36.352447

[4378 rows x 3 columns]

In [3]:
korea_map = folium.Map(location=[36.7888, 127.852], zoom_start= 7, tiles = 'CartoDB positron')

korea_map

In [6]:
for name, lat, lng in zip(df.corp_name, df.latitude, df.longitude):
    folium.Marker([lat, lng], popup=name).add_to(korea_map)

korea_map